//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoDServer.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Naming {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Naming() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CoDServer.Resource.Naming", typeof(Naming).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Dragon Slaying Saber.
        /// </summary>
        public static string DragonSaber {
            get {
                return ResourceManager.GetString("DragonSaber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Heaven Reliant Sword.
        /// </summary>
        public static string HeavenSword {
            get {
                return ResourceManager.GetString("HeavenSword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jin Yong.
        /// </summary>
        public static string JinYong {
            get {
                return ResourceManager.GetString("JinYong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shadowless Spear.
        /// </summary>
        public static string ShadowlessSpear {
            get {
                return ResourceManager.GetString("ShadowlessSpear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zhang Sanfeng.
        /// </summary>
        public static string ZhangSanfeng {
            get {
                return ResourceManager.GetString("ZhangSanfeng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zhang Wuji.
        /// </summary>
        public static string ZhangWuji {
            get {
                return ResourceManager.GetString("ZhangWuji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zhu Yuanzhang.
        /// </summary>
        public static string ZhuYuanzhang {
            get {
                return ResourceManager.GetString("ZhuYuanzhang", resourceCulture);
            }
        }
    }
}
